Algoritmo "exercicio12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval(" BORA VERIFICAR SE PASSOU")
    escreval("")
    
    escreva("SUA NOTA: ")
    leia(nota)
    
    //Agora vou usar as condições
    se (nota >= 70) entao
       escreval("Parabeéns, voce PASSOU!! ")
    senao
         escreval("Infelizmente não passou, tente ano que vem")
    fimse

Fimalgoritmo