Algoritmo "exercicio10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/09/2026
Var
// Seção de Declarações das variáveis 
   senha,senhac: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   senhac <-2026
   //declarando o valor da senha
   escreva("SENHA: ")
   leia(senha)
   
   enquanto senha <> senhac faca
            escreval("Incorreta, TENTE NOVAMENTE :(")
            escreva("SENHA: ")
            leia(senha)
   fimenquanto
   //Como a exigencia pro enquanto é senha ser diferente, não preciso criar algo a mais dentro.
   escreva("")
   escreval("ACESSO LIBERADO!! ;)")
   

Fimalgoritmo