Algoritmo "exercicio2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026

Var
// Seção de Declarações das variáveis 
     nome: caractere
     
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Diga seu nome, para o jogo do bicho: ")
   leia(nome)
   
   
   aguarde(2000)

   escreval("Boa tarde, "+ nome + "!")

Fimalgoritmo