Algoritmo "exercicio13"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
    matricula, cracha: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("  Vamos verificar se pode entrar no laboratorio ")
   escreval("")
   
   escreval("Voce tem matricula? (S/N)")
   leia(matricula)
   
   escreval("Voce tem crachá? (S/N)")
   leia(cracha)
   //prof me ajudou nessa
   Se ((matricula = "s") e (cracha = "s")) entao
        escreval("Beleza, pode entrar ai!")
   senao
        escreval("Precisa ter MATRICULA e CRACHÁ para poder entrar")
   fimse
   

   //exercicio do LULA

Fimalgoritmo