Algoritmo "exercicioslide2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var
// Seção de Declarações das variáveis 
   senha: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("| - Digite sua senha: ")
   leia(senha)
   
   enquanto senha <> 1234 faca
            escreval("SENHA INCORRETA")
            escreval("Tente Novamente")
            leia(senha)
   fimenquanto //finalizando o algoritmo
   escreval("Senha correta!!")
Fimalgoritmo