Algoritmo "exercicioSlide"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var
// Seção de Declarações das variáveis 
   n,i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Até quanto deseja contar?")
   leia(n)
   
   i<- 1  //começa em 1, pois a contagem começa....
   
   escreval("Contando até", n)
   
   enquanto i <= n faca
            escreval(i)
            i <- i+1
   fimenquanto
   
   escreval("Contagem finalizada")

Fimalgoritmo