Algoritmo "exercicio7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2026
Var
// Seção de Declarações das variáveis 
   i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Esses são numeros pares de 1 a 100: ")

   para i de 1 ate 100 faca
        se i % 2 = 0 entao  //demorei um pouco pra entender que 1º é o para e 2º viria o Se
           escreval(i)
        fimse
   fimpara

Fimalgoritmo