Algoritmo "exercicio6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var
// Seção de Declarações das variáveis 
   i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Estou imprimindo os numeros de 10 até 1")

   i <- 10
   
   enquanto i >= 1 faca
            escreval(i)
            i <- i-1
   fimenquanto        //feliz ano novo (só pra comentar)
   
   escreval("Feliz ano novo!!")

Fimalgoritmo