Algoritmo "exercicio4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var
// Seção de Declarações das variáveis 
   N,i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" Escreva o numero: ")
   leia(N)
   
   //bem simples
   para i de 1 ate N passo 2 faca
        escreval("Returno: ", i)
   fimpara

Fimalgoritmo