Algoritmo "exercicio3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
   numero: inteiro
   dobro: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Escreva um numero")
   leia(numero)
   
   dobro <- numero*2
   
   escreva("O dobro de", numero,"é: ", dobro)





Fimalgoritmo